apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeflow-trainer-public
  namespace: kubeflow-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - kubeflow-trainer-public
  verbs:
  - get
